"""description of your changes

Revision ID: 04f9ae5e35e8
Revises: 
Create Date: 2025-01-03 02:59:29.875099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04f9ae5e35e8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('admin')
    op.drop_table('course')
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=512, collation='Latin1_General_CI_AS'),
               nullable=False)
        batch_op.alter_column('gender',
               existing_type=sa.VARCHAR(length=10, collation='Latin1_General_CI_AS'),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('phone',
               existing_type=sa.VARCHAR(length=15, collation='Latin1_General_CI_AS'),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('address',
               existing_type=sa.VARCHAR(length=200, collation='Latin1_General_CI_AS'),
               type_=sa.String(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.alter_column('address',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=200, collation='Latin1_General_CI_AS'),
               existing_nullable=True)
        batch_op.alter_column('phone',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=15, collation='Latin1_General_CI_AS'),
               existing_nullable=True)
        batch_op.alter_column('gender',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=10, collation='Latin1_General_CI_AS'),
               existing_nullable=True)
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=512, collation='Latin1_General_CI_AS'),
               nullable=True)

    op.create_table('course',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100, collation='Latin1_General_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=300, collation='Latin1_General_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('duration', sa.FLOAT(precision=53), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='PK__course__3213E83F0F3E2603')
    )
    op.create_table('admin',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=50, collation='Latin1_General_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=100, collation='Latin1_General_CI_AS'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='PK__admin__3213E83F6E0E4C77')
    )
    # ### end Alembic commands ###
